### ISSUE TITLE
Cannot provide SerializersModule to Bundle[Encoder/Decoder]

### ISSUE THREAD

**Issue by AntonAzaryan** [AhmedMourad0/bundlizer#5]
Example: 

```
@Serializable
data class AppState(
    val slices: Map<String, @Polymorphic Any>
)

@Serializable
data class FeatureState1(...)

@Serializable
data class FeatureState2(...)
```

My `@Polymorphic Any` type parameter can be FeatureState1 or FeatureState2. So what i do :

```
val module = SerializersModule {
    polymorphic(Any::class) {
        subclass(FeatureState1::class)
        subclass(FeatureState2::class)
    }
}
```

And then i can't provide "module" for Bundle[Encoder/Decoder] in 

`Bundlizer.bundle(AppState.serializer(), appstate)`

so got error here ^.

It would be good to have optional parameter of type SerializersModule with default value "EmptySerializersModule".

**Comment by AhmedMourad0** [comment]
That makes sense, I'll be looking into it very shortly.
