### ISSUE TITLE
How to set/get using a key?

### ISSUE THREAD

**Issue by paulocoutinhox** [AhmedMourad0/bundlizer#7]
Hi,

How to set/get using a key?

Im asking because my bundle need have other keys inside. There is any problem with this or the bundle can only have one bundlizer item?

Thanks.

**Comment by paulocoutinhox** [comment]
I made using this way:

```
val fragment = BottomSheetMenuFragment()

val configBundle = config.bundle(BottomSheetMenuConfig.serializer())
val args = Bundle()
args.putBundle("config", configBundle)

fragment.arguments = args
return fragment
```

This is the correct way to do it?

Thanks.

**Comment by AhmedMourad0** [comment]
Hello there, yup that is the correct way to do it in order to avoid key conflicts.
